matrix:
  include:

    # static notebook environment
    - env: static-notebook
      language: node_js
      node_js:
        - "lts/*"
        - "8"

      install:
        - npm install

      script:
        - npm run lint
        - npm test

      before_deploy:
        # test commenting the cp out for now, b/c going forward we'll be using the
        # django server to serve the landing page
        # - cp prod/iodide.${TRAVIS_BRANCH}.html prod/index.html
        - >
          if [ -n "$TRAVIS_TAG" ]; then
            mkdir prod;
            git clone https://github.com/iodide-project/dist.git --depth 1 dist;
            # Get existing releases from iodide-project/dist so we don't overwrite them
            cp -r dist/* prod;
            export EDITOR_ORIGIN = "https://iodide.io/dist";
            export EVAL_FRAME_ORIGIN = "https://iodide.app";
            export APP_VERSION_SRING = $TRAVIS_TAG;
            npm run build-prod-client-only;
          else
            if [ $TRAVIS_BRANCH = "master" ]; then
              export EDITOR_ORIGIN = "https://extremely-alpha.iodide.io";
              export EVAL_FRAME_ORIGIN = "https://extremely-alpha.iodide.app";
            else
              export EDITOR_ORIGIN="https://iodide.io/stable";
              export EVAL_FRAME_ORIGIN="https://iodide.app/stable";
            fi
            export APP_VERSION_STRING = $TRAVIS_BRANCH;
            npm run build-dev-client-only;
          fi

      deploy:
        - provider: pages
          github-token: "$GITHUB_TOKEN"
          skip-cleanup: true
          keep-history: false
          repo: iodide-project/stable
          verbose: false
          local-dir: build
          target-branch: master
          on:
            branch: stable

        - provider: pages
          github-token: "$GITHUB_TOKEN"
          skip-cleanup: true
          keep-history: false
          repo: iodide-project/master-eval
          fqdn: extremely-alpha.iodide.app
          verbose: false
          local-dir: build
          target-branch: master
          on:
            branch: master

        - provider: pages
          github-token: "$GITHUB_TOKEN"
          skip-cleanup: true
          keep-history: true
          repo: iodide-project/dist
          verbose: true
          local-dir: prod
          target-branch: master
          on:
            tags: true
            
        - provider: pages
          github-token: "$GITHUB_TOKEN"
          skip-cleanup: true
          keep-history: true
          repo: iodide-project/dist-eval
          verbose: true
          local-dir: prod
          target-branch: master
          on:
            tags: true

    # experimental iodide server
    - env: server
      language: node_js
      node_js:
        - "lts/*"
      sudo: required
      services:
        - docker

      before_install:
        # need a more recent version of docker-compose than is currently supported by travis
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
        # Shut down postgres because it blocks our db container's port map to :5432
        - sudo service postgresql stop
        # Wait for it to stop
        - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

      install:
        - npm install

      script:
        - cp .env-dist .env
        - make build
        # bring up docker containers and wait for db setup to complete (otherwise
        # our tests might try to bring up another instance of the db, which is a
        # race condition)
        # (FIXME: need some sort of timeout here)
        - docker-compose up -d
        - docker-compose run server bash -c "while ! echo > /dev/tcp/db/5432 > /dev/null 2>&1; do sleep 1 && echo waiting for db; done"
        # run actual tests
        - make flake8
        - make test

env:
  global:
    secure: "xdWpZfWZvPTzY25ayFaC/62vceytA3jT6RdQIlhp9QOKvNYe5qiD4eviP+LflJhvc7gTNysYIidtWLhYqSqWU7GRLeHtfplJ6hXsZrPnI9CJiG+Ng9OIp7VShPb+q1RurdHMY/33TEXTk95KhA+9tQ4s8hyri1boqX48xcPWoIWH/ozqwkz3H0rWjzc7HX02D+TcE19PEdpH8eJCQa7dwAygFqc/kx5B5PoBZB6R756614CjaaPiQft3OfI8k7R15lExinoMiHpTFLmcFODZ8UPm0t2AD6GqmzRrXyTRqPkRQNRYG2mAr8RMaPkYk26piPmlNFKoWanPnu+Iq+plT6Adc57P0VPYT/a2QyiGhD1+5n08Bflz5AdDrSN/Qb3PXJDCQscqDGUjwfMKT+Jigt2L6Q1jSe3BZrhikb2+koSRS6g+bCpfu23iS2fog2P3n8npGv90EnUp3Zdgj8XcARLXxxb6hfFDZYUq2H8dEasKvxrZFDGjDECA5m4olNkZHSgHsU2zqNgzvNBQcICQ6+rHn5CWmO8WD5er+BnJoUl+mARSxhmkqdtVF+oR0KOhAWzeRvCEwqjHJ2o33kd0/cifjjc3w3ODNi8kXcpFYW5rQVHvRTx9dPXbhvRT2TyeZViA/j6PUMAcqeLw0Lgy57dFmE/0M8oJzqM8sz+mJF4="
