site_name: Iodide Documentation
site_url: https://iodide-project.github.io/iodide/
repo_url: https://github.com/iodide-project/iodide/
theme: mkdocs
extra_css: [extra.css]
nav:
  - Index: index.md
markdown_extensions:
  - markdown_include.include

