site_name: Iodide Documentation
site_url: https://docs.iodide.io/
repo_url: https://github.com/iodide-project/iodide/
theme: mkdocs
extra_css: [extra.css]
nav:
  - Index: index.md
markdown_extensions:
  - markdown_include.include
plugins:
    - markdownmermaid
extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

