[tool.black]
line-length = 100
exclude = "migrations/"

[tool.isort]
line_length = 100
default_section = "THIRDPARTY"
known_first_party = "server,helpers"
skip_glob = "**/migrations/*"
# For compatibility with black:
multi_line_output = 3
include_trailing_comma = "True"
force_grid_wrap = 0
use_parentheses = "True"
